import React, { createContext, useContext, type ReactNode } from 'react';

export type ModalSize = 'sm' | 'md' | 'lg' | 'xl' | 'full';

export interface ModalContextValue {
  isOpen: boolean;
  dismissible: boolean;
  size: ModalSize;
  close: () => void;
  /**
   * id the header's title must carry, referenced by the dialog's
   * `aria-labelledby`. Generated by the factory because the container and the
   * header are composed from the schema, never as JSX siblings.
   */
  titleId: string;
  /** id the header's description must carry, for `aria-describedby`. */
  descriptionId: string;
}

const ModalContext = createContext<ModalContextValue | null>(null);

export function ModalProvider({
  value,
  children,
}: {
  value: ModalContextValue;
  children: ReactNode;
}) {
  return <ModalContext.Provider value={value}>{children}</ModalContext.Provider>;
}

export function useModalContext(): ModalContextValue {
  const ctx = useContext(ModalContext);
  if (!ctx) {
    throw new Error(
      'useModalContext must be used inside a ModalProvider. This component is only rendered by ModalFactory.'
    );
  }
  return ctx;
}

export function useOptionalModalContext(): ModalContextValue | null {
  return useContext(ModalContext);
}
